language: go
dist: xenial
sudo: false
go:
  - stable
before_install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
  # workaround for now:
  - GOOS=windows go get -t -v ./...
  - go get -t -v ./...
jobs:
  include:
    - script: true # make all
    - stage: Run Test Coverage
      script: make cover
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Build Release
      script:
        - make release
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/idbenchmark-darwin-amd64
          - cross/idbenchmark-darwin-amd64.md5
          - cross/idbenchmark-darwin-amd64.sha256
          - cross/idbenchmark-darwin-386
          - cross/idbenchmark-darwin-386.md5
          - cross/idbenchmark-darwin-386.sha256
          - cross/idbenchmark-freebsd-amd64
          - cross/idbenchmark-freebsd-amd64.md5
          - cross/idbenchmark-freebsd-amd64.sha256
          - cross/idbenchmark-freebsd-386
          - cross/idbenchmark-freebsd-386.md5
          - cross/idbenchmark-freebsd-386.sha256
          - cross/idbenchmark-linux-arm
          - cross/idbenchmark-linux-arm.md5
          - cross/idbenchmark-linux-arm.sha256
          - cross/idbenchmark-linux-arm64
          - cross/idbenchmark-linux-arm64.md5
          - cross/idbenchmark-linux-arm64.sha256
          - cross/idbenchmark-linux-amd64
          - cross/idbenchmark-linux-amd64.md5
          - cross/idbenchmark-linux-amd64.sha256
          - cross/idbenchmark-linux-386
          - cross/idbenchmark-linux-386.md5
          - cross/idbenchmark-linux-386.sha256
          - cross/idbenchmark-solaris-amd64
          - cross/idbenchmark-solaris-amd64.md5
          - cross/idbenchmark-solaris-amd64.sha256
          - cross/idbenchmark-windows-amd64.exe
          - cross/idbenchmark-windows-amd64.exe.md5
          - cross/idbenchmark-windows-amd64.exe.sha256
          - cross/idbenchmark-windows-386.exe
          - cross/idbenchmark-windows-386.exe.md5
          - cross/idbenchmark-windows-386.exe.sha256
        skip_cleanup: true
        on:
          tags: true
        github-token: $GITHUB_TOKEN
